### ISSUE TITLE
error with dependencies 

### ISSUE THREAD

**Issue by andrenalina1** [padlocbio/padloc#28] opened 2023-04-20 18:00 UTC
Hello
We've recently installed the padloc program, but we're having trouble getting it to work. Although we have obtained resulting files, we are always shown the following error:

 - using the command : padloc --fna genome.fasta

- we get

[14:23:49] >> Predicting protein-coding genes with prodigal
[14:23:57] >> Scanning genome.fasta for defence system proteins
[14:26:53] >> Searching genome.fasta for defence systems
Error: package or namespace load failed for ‘tidyverse’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/home/user/.conda/envs/PadLoc/lib/R/library/stringi/libs/stringi.so':
  libicui18n.so.58: cannot open shared object file: No such file or directory
Execution halted
[14:26:54] ERROR >> errexit on line 397

apparently the tidyverse package is not working correctly. Could you help us understand the problem and solve it?

**Comment by xinleee** [comment] 2023-07-06 12:53
Finally found it from google:https://github.com/tidyverse/haven/issues/363
For people who googled to here, you may try this:
withr::with_makevars(c(PKG_LIBS = "-liconv"), install.packages("haven"), assignment = "+=")
It seems someone create a typo in somewhere.

**Comment by leightonpayne** [comment] 2023-09-27 01:57
I am unable to reproduce this issue, when making a fresh install via `conda`, I don't run into any errors. I'm going to assume this is solved and close the issue, but feel free to re-open with more information if you're still having trouble.

**Closed by leightonpayne** 2023-09-27 01:57 UTC
